#!/bin/sh
if [ "$#" -ne 1 ]; then
    echo "Usage : ./run <file with extension and path>"
    exit 2
else
    printf "Enter a word (& for epsilon) : " && read var1
    printf "$var1" > word_pipe & ./parser < ${1}
fi